[package]
org = "ballerinax"
name = "stan"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "streaming"]
repository = "https://github.com/ballerina-platform/module-ballerinax-stan"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/java-nats-streaming-2.2.3.jar"

[[platform.java11.dependency]]
path = "./lib/jnats-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/stan-native-@project.version@.jar"

[build-options]
observabilityIncluded=true
