[package]
org = "ballerinax"
name = "stan"
version = "2.2.1"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "streaming"]
repository = "https://github.com/ballerina-platform/module-ballerinax-stan"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "./lib/java-nats-streaming-2.2.3.jar"

[[platform.java11.dependency]]
path = "./lib/jnats-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/stan-native-2.2.1.jar"

[build-options]
observabilityIncluded=true
